(function($){(function($){var defaultOptions={'href':null,'selector':null,'options':null,'delayOpen':200,'callbackOpen':$.noop,'callbackClose':$.noop};var JqFensterApi=function($elem,options){this.holder=$elem.data('jqFensterHolder')||null;this.element=$elem;this.options=$.extend({},defaultOptions);this.setOptions(options);if(!this.options.selector&&this.element.selector){this.options.selector=this.element.selector;}
if(!this.element.hasClass('jqFenster')){this.element.addClass('jqFenster');this._init();}};JqFensterApi.prototype={close:function(){if(!this.getHolder()){return this;}
this.options.callbackClose.call(null,this.getHolder());this.getHolder().trigger('jqFensterClose');this.setHolder(null);return this;},destroy:function(){if(this.element.data('jqFensterDestroyable')){this.element.remove();}},open:function(cb){var cbToExecute=function(){this.options.callbackOpen.call(null,this.getHolder());if($.type(cb)==='function'){cb.call(this);}
return this;};if(this.getHolder()){return cbToExecute.call(this);}
this.element.trigger('click');setTimeout(function(){this.setHolder(this.element.data('jqFensterHolder'));cbToExecute.call(this);}.bind(this),this.options.delayOpen);return this;},reInit:function(){this.close();var that=this;setTimeout(function(){if(that.element.data('modalLocked')){return that.reInit();}
that._init().open();},50);return this;},getHolder:function(){return this.holder;},getAncestor:function(){return this.getHolder()?this.getHolder().data('jqFensterAncestor'):null;},setHolder:function(obj){this.holder=obj;return this;},setOptions:function(options){$.extend(this.options,options||{});return this;},_init:function(){if(this.options.href!==null){this.element.data('href',this.options.href);}
if(this.options.selector!==null){this.element.data('selector',this.options.selector);}
if(this.options.options){this.element.data('options',this.options.options);}
return this;}};$.fn.fenster=function(options){return new JqFensterApi(this,options);};$.extend({fensterFinder:function(target){var $target=$(target),$elem;if($target.data('jqFensterHolder')){return $target.fenster($target.data('options'));}
$elem=$target.closest('.jqFensterHolder');if($elem.length){return $($elem.data('jqFensterAncestor')).fenster();}
return null;},fenster:function(options){var $elem=$('<a />',{css:{display:'none'}}).data('jqFensterDestroyable',true);$('body').append($elem);if($.type(options)==='string'){options={'selector':options};}
return $elem.fenster(options);}});}(jQuery));(function(doc,win,$){$.jqFensterOptions={noOverlay:false,animationSpeed:0,callbackOpen:null,callbackClose:null,template:null,width:true};$.jqFensterOptions.template={prepare:function(){return this.children().hide();},inject:function(content){this.empty().append(content);},cleanupRemote:function(){return this.remove();},cleanupSelector:function(){return this.children().hide().unwrap();}};var JqFenster=function(options,$element){this.options=$.extend({},options);this.element=$element;this.overlay=null;this.holder=null;this._init=function(){var that=this;this.holder=$('<div/>').addClass('jqFensterHolder');$.data(this.holder.get(0),'jqFenster',this);if($element.data('options')){try{$.extend(this.options,$.type($element.data('options'))==='object'?$element.data('options'):$.parseJSON($element.data('options').replace(/([a-zA-Z]+):/g,'"$01":')));}catch(e){$.error(['jqFenster: incorrect JSON provided (check the code of a link)',$element,e.toString()]);}}
if($.type(this.options.callbackOpen)==='string'){this.options.callbackOpen=win[this.options.callbackOpen];}
if($.type(this.options.callbackClose)==='string'){this.options.callbackClose=win[this.options.callbackClose];}
if($.isFunction(this.options.callbackOpen)){this.holder.bind('jqFensterCallbackOpen',function(){return that.options.callbackOpen(that.getElement());});}
if($.isFunction(this.options.callbackClose)){this.holder.bind('jqFensterCallbackClose',function(){return that.options.callbackClose(that.getElement());});}};};JqFenster.prototype={getHolder:function(){return this.holder;},getElement:function(){return this.element;},getOverlay:function(){return this.overlay;},open:function(){if(this.isLocked()){return false;}
this._init();this.setLock(true);$('body').append(this.getHolder());if(this.getElement().data('selector')){return this.create($(this.getElement().data('selector')));}
var that=this;if(this.options.template.beforeLoad){this.options.template.beforeLoad.call(this.getHolder());}
$.get((this.getElement().data('href')||this.getElement().attr('href'))).done(function(data){if(that.options.template.afterLoad){that.options.template.afterLoad.call(that.getHolder());}
that.create(data);});return this;},show:function(){var $elem=this.options.template.prepare.call(this.getHolder());if(!$elem.height()){var that=this;setTimeout(function(){that.show();},30);return this;}
if(this.options.width!==false){this.getHolder().children().css('width',this.options.width===true?$elem.width():this.options.width);}
$elem.show();return this;},create:function(target){var that=this,$holder=this.getHolder(),$element=this.getElement(),$injected=this.options.template.inject.call($holder,target);this.show();$holder.bind('jqFensterClose',function(){if($.type(that.getOverlay())==='object'){that.getOverlay().close();that.setOverlay(null);return that;}
return that.close();});$holder.find('.jqFensterClose').bind('click',function(){$holder.trigger('jqFensterClose');return false;});$holder.data('jqFensterAncestor',$element);$element.data('jqFensterHolder',$holder);if(this.options.noOverlay||!$.isFunction($.fn.jqEbony)){$holder.hide().fadeIn(this.options.animationSpeed,function(){$holder.trigger('jqFensterCallbackOpen');});return false;}
this.setOverlay($($holder).jqEbony({clickCloseArea:$injected,animationSpeed:this.options.animationSpeed,callbackClose:function(){return that.close.call($.data(this.getElement().get(0),'jqFenster'));},callbackOpen:function(){return $holder.trigger('jqFensterCallbackOpen');}}));this.getOverlay().open();return false;},close:function(){var $element=this.getElement(),$holder=this.getHolder(),that=this,cb=function(){$holder.trigger('jqFensterCallbackClose');$.proxy($element.data('selector')?that.options.template.cleanupSelector:that.options.template.cleanupRemote,$(this))();$element.removeData('jqFensterLocked').removeData('jqFensterHolder');return that;};if($.isFunction($.fn.jqEbony)&&!this.getOverlay()){$holder.hide();return cb();}
$holder.fadeOut(this.getOverlay()?0:this.options.animationSpeed,cb);return this;},isLocked:function(){return this.getElement().data('jqFensterLocked');},setLock:function(marker){return this.getElement().data('jqFensterLocked',!!marker);},setOverlay:function(overlay){this.overlay=overlay;return this;}};var jqFensterCallback=function(){(new JqFenster($.jqFensterOptions,$(this))).open();return false;};if($.isFunction($.fn.live)){$('.jqFenster').live('click',jqFensterCallback);}else{$(doc).on('click','.jqFenster',jqFensterCallback);}}(document,window,jQuery));(function($){$.jqFensterOptions.template={prepare:function(){return this.find('td.jqFensterContent').children().hide();},inject:function(content){return this.append('<table class="jqFensterContainer"><tr><td class="jqFensterContent"></td></tr></table>').find('td.jqFensterContent').append(content);},cleanupRemote:function(){return this.remove();},cleanupSelector:function(){this.parent().append(this.find('td.jqFensterContent').children().hide());return this.remove();},beforeLoad:function(){return this.append('<div class="jqFensterLoading"><p></p></div>');},afterLoad:function(){return this.find('div.jqFensterLoading').remove();}};}(jQuery));(function(doc,$){$.jqEbonyOptions={'opacity':0.7,'zIndex':99999,'escapeCloses':true,'clickCloses':true,'clickCloseArea':null,'callbackClose':null,'callbackCloseBefore':null,'callbackOpen':null,'animationSpeed':0,'color':[0,0,0]};var JqEbony=function(options,element){this.layout=null;this.element=element;this.options=$.extend($.jqEbonyOptions,options||{});};JqEbony.prototype={getLayout:function(){return this.layout;},getIndexZ:function(){return parseInt($('body').data('jqEbony')||this.getOptions().zIndex,10);},getOptions:function(){return this.options;},getElement:function(){return this.element;},setIndexZ:function(val){$('body').data('jqEbony',val);return this;},setLayout:function(layout){this.layout=layout;return this;},hasLayout:function(){return!!this.layout;},open:function(){if(this.hasLayout()){return this;}
this.setLayout(this.getDefaultLayout());this._setListeners();this.getElement().wrapAll(this.getLayout());this._transform().setIndexZ(this.getIndexZ()+1);var that=this;this.getElement().hide().parent().fadeIn(this.getOptions().animationSpeed,function(){that.getElement().css('z-index',that.getIndexZ()).fadeIn(parseInt(that.getOptions().animationSpeed/2,10),function(){if($.isFunction(that.getOptions().callbackOpen)){that.getOptions().callbackOpen.call(that);}});});return this;},close:function(){if(!this.hasLayout()){return this;}
var that=this,$element=this.getElement();if($.isFunction(this.getOptions().callbackCloseBefore)){this.getOptions().callbackCloseBefore($element);}
$element.parent().fadeOut(this.getOptions().animationSpeed,function(){$element.unwrap();that._revert();that.setLayout(null);if($.isFunction(that.getOptions().callbackClose)){that.getOptions().callbackClose.call(that);}});return this;},getDefaultLayout:function(){var rgba=[];rgba.push(this.getOptions().color);rgba.push(this.getOptions().opacity);return $('<div />').addClass('jqEbony').css({'display':'none','position':'fixed','right':0,'top':0,'left':0,'bottom':0,'overflow':'auto','z-index':this.getIndexZ(),'background':'rgba('+rgba.join(',')+')'});},_setListeners:function(){var that=this;if(this.options.escapeCloses){$(doc).one('keyup.jqEbony',function(event){if((event.keyCode||event.which)===27){event.stopImmediatePropagation();return that.close();}});$._data(doc,'events').keyup.unshift($._data(doc,'events').keyup.pop());}
if(this.options.clickCloses){var $clickArea=this.getElement().parent();if(this.getOptions().clickCloseArea!==null){$clickArea=$(this.getOptions().clickCloseArea);}
this.getElement().bind('click.jqEbony',function(e){var $target=$(e.target);$('>*',$clickArea).each(function(){if(e.target!==this&&!$(this).is('script')&&!$(this).is('style')&&$target.closest('html',this).length){return that.close();}});});}
return this;},_transform:function(){var $elem=this.getElement(),$body=$('body'),$html=$('html'),old={'outerWidth':$body.outerWidth(true),'marginRight':parseInt($('body').css('margin-right'),10),'scrollTop':$html.scrollTop()};$elem.data('jqEbony',this);this.getLayout().data('jqEbonyData',{'element':{'position':$elem.css('position'),'display':$elem.css('display'),'visibility':$elem.css('visibility')},'html':{'overflow':$('html').css('overflow-y')},'body':{'margin-right':$('body').css('margin-right')}});$html.css('overflow','hidden');$body.css('margin-right',$body.outerWidth(true)-old.outerWidth+old.marginRight);$html.scrollTop(old.scrollTop);return this;},_revert:function(){this.setIndexZ(this.getIndexZ()-1);if(!this.getLayout().data('jqEbonyData')){return this;}
var $layout=this.getLayout(),oldScroll=$('html').scrollTop();if(!$('div.jqEbony').length){$('body').css($layout.data('jqEbonyData').body);$('html').css($layout.data('jqEbonyData').html).scrollTop(oldScroll);}
this.getElement().css($layout.data('jqEbonyData').element).removeData('jqEbonyData').removeData('jqEbony');return this;}};$.fn.jqEbony=function(options){return(this.data('jqEbony')||new JqEbony(options,$(this)));};}(document,jQuery));})(jQuery);